// <auto-generated />
using System;
using AutoMarket.Server.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMarket.Server.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoMarket.Server.Core.Models.BodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Седан"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Хетчбек"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Мінівен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Купе"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Позашляховик / Кросовер"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveTrainId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GearBoxTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("ModificationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TechnicalConditionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("DriveTrainId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GearBoxTypeId");

                    b.HasIndex("GenerationId");

                    b.HasIndex("ModelId");

                    b.HasIndex("ModificationId");

                    b.HasIndex("TechnicalConditionId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.DriveTrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriveTrains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Передній"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Задній"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Повний"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Бензин"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Газ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Газ метан / Бензин"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Газ пропан-бутан / Бензин"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Гібрид (HEV)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Гібрид (PHEV)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Дизель"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Електро"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.GearBoxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GearBoxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ручна / Механіка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Автомат"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Типтронік"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Робот"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Варіатор"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Generation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearFrom")
                        .HasColumnType("int");

                    b.Property<int>("YearTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Generations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "E39",
                            YearFrom = 1995,
                            YearTo = 2000
                        },
                        new
                        {
                            Id = 2,
                            Name = "E39 [restyling]",
                            YearFrom = 2000,
                            YearTo = 2004
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePathToDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProducingCountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProducingCountryId");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "https://localhost:7119/MakeIcons\\bmw.svg",
                            Name = "BMW",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "https://localhost:7119/MakeIcons\\toyota.svg",
                            Name = "Toyota",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "https://localhost:7119/MakeIcons\\audi.svg",
                            Name = "Audi",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "https://localhost:7119/MakeIcons\\maybach.svg",
                            Name = "Maybach",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "https://localhost:7119/MakeIcons\\mercedes benz.svg",
                            Name = "Mercedes-Benz",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "https://localhost:7119/MakeIcons\\opel.svg",
                            Name = "Opel",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "https://localhost:7119/MakeIcons\\porsche.svg",
                            Name = "Porsche",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "https://localhost:7119/MakeIcons\\smart.svg",
                            Name = "Smart",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "https://localhost:7119/MakeIcons\\volkswagen.svg",
                            Name = "Volkswagen",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "https://localhost:7119/MakeIcons\\bmw.svg",
                            Name = "BMW-Alpina",
                            ProducingCountryId = 1
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "https://localhost:7119/MakeIcons\\daihatsu.svg",
                            Name = "Daihatsu",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "https://localhost:7119/MakeIcons\\honda.svg",
                            Name = "Honda",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "https://localhost:7119/MakeIcons\\isuzu.svg",
                            Name = "Isuzu",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "https://localhost:7119/MakeIcons\\lexus.svg",
                            Name = "Lexus",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "https://localhost:7119/MakeIcons\\mazda.svg",
                            Name = "Mazda",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "https://localhost:7119/MakeIcons\\mitsubishi.svg",
                            Name = "Mitsubishi",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "https://localhost:7119/MakeIcons\\nissan.svg",
                            Name = "Nissan",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "https://localhost:7119/MakeIcons\\subaru.svg",
                            Name = "Subaru",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "https://localhost:7119/MakeIcons\\suzuki.svg",
                            Name = "Suzuki",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "https://localhost:7119/MakeIcons\\acura.svg",
                            Name = "Acura",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "https://localhost:7119/MakeIcons\\infiniti.svg",
                            Name = "Infiniti",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "https://localhost:7119/MakeIcons\\scion.svg",
                            Name = "Scion",
                            ProducingCountryId = 2
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "https://localhost:7119/MakeIcons\\aixam.svg",
                            Name = "Aixam",
                            ProducingCountryId = 3
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "https://localhost:7119/MakeIcons\\citroen.svg",
                            Name = "Citroen",
                            ProducingCountryId = 3
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "https://localhost:7119/MakeIcons\\peugeot.svg",
                            Name = "Peugeot",
                            ProducingCountryId = 3
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "https://localhost:7119/MakeIcons\\renault.svg",
                            Name = "Renault",
                            ProducingCountryId = 3
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "https://localhost:7119/MakeIcons\\alpine.svg",
                            Name = "Alpine",
                            ProducingCountryId = 3
                        },
                        new
                        {
                            Id = 28,
                            ImagePath = "https://localhost:7119/MakeIcons\\bugatti.svg",
                            Name = "Bugatti",
                            ProducingCountryId = 3
                        },
                        new
                        {
                            Id = 29,
                            ImagePath = "https://localhost:7119/MakeIcons\\cadillac.svg",
                            Name = "Cadillac",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 30,
                            ImagePath = "https://localhost:7119/MakeIcons\\chevrolet.svg",
                            Name = "Chevrolet",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 31,
                            ImagePath = "https://localhost:7119/MakeIcons\\chrysler.svg",
                            Name = "Chrysler",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 32,
                            ImagePath = "https://localhost:7119/MakeIcons\\ford.svg",
                            Name = "Ford",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 33,
                            ImagePath = "https://localhost:7119/MakeIcons\\jeep.svg",
                            Name = "Jeep",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 34,
                            ImagePath = "https://localhost:7119/MakeIcons\\buick.svg",
                            Name = "Buick",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 35,
                            ImagePath = "https://localhost:7119/MakeIcons\\dodge.svg",
                            Name = "Dodge",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 36,
                            ImagePath = "https://localhost:7119/MakeIcons\\eagle.svg",
                            Name = "Eagle",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 37,
                            ImagePath = "https://localhost:7119/MakeIcons\\gmc.svg",
                            Name = "GMC",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 38,
                            ImagePath = "https://localhost:7119/MakeIcons\\hummer.svg",
                            Name = "Hummer",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 39,
                            ImagePath = "https://localhost:7119/MakeIcons\\lincoln.svg",
                            Name = "Lincoln",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 40,
                            ImagePath = "https://localhost:7119/MakeIcons\\mercury.svg",
                            Name = "Mercury",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 41,
                            ImagePath = "https://localhost:7119/MakeIcons\\oldsmobile.svg",
                            Name = "Oldsmobile",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 42,
                            ImagePath = "https://localhost:7119/MakeIcons\\pontiac.svg",
                            Name = "Pontiac",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 43,
                            ImagePath = "https://localhost:7119/MakeIcons\\plymouth.svg",
                            Name = "Plymouth",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 44,
                            ImagePath = "https://localhost:7119/MakeIcons\\saturn.svg",
                            Name = "Saturn",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 45,
                            ImagePath = "https://localhost:7119/MakeIcons\\tesla.svg",
                            Name = "Tesla",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 46,
                            ImagePath = "https://localhost:7119/MakeIcons\\fisker.svg",
                            Name = "Fisker",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 47,
                            ImagePath = "https://localhost:7119/MakeIcons\\ram.svg",
                            Name = "Ram",
                            ProducingCountryId = 4
                        },
                        new
                        {
                            Id = 48,
                            ImagePath = "https://localhost:7119/MakeIcons\\daewoo.svg",
                            Name = "Daewoo",
                            ProducingCountryId = 5
                        },
                        new
                        {
                            Id = 49,
                            ImagePath = "https://localhost:7119/MakeIcons\\hyundai.svg",
                            Name = "Hyundai",
                            ProducingCountryId = 5
                        },
                        new
                        {
                            Id = 50,
                            ImagePath = "https://localhost:7119/MakeIcons\\kia.svg",
                            Name = "Kia",
                            ProducingCountryId = 5
                        },
                        new
                        {
                            Id = 51,
                            ImagePath = "https://localhost:7119/MakeIcons\\genesis.svg",
                            Name = "Genesis",
                            ProducingCountryId = 5
                        },
                        new
                        {
                            Id = 52,
                            ImagePath = "https://localhost:7119/MakeIcons\\skoda.svg",
                            Name = "Skoda",
                            ProducingCountryId = 6
                        },
                        new
                        {
                            Id = 53,
                            ImagePath = "https://localhost:7119/MakeIcons\\alfa romeo.svg",
                            Name = "Alfa Romeo",
                            ProducingCountryId = 7
                        },
                        new
                        {
                            Id = 54,
                            ImagePath = "https://localhost:7119/MakeIcons\\ferrari.svg",
                            Name = "Ferrari",
                            ProducingCountryId = 7
                        },
                        new
                        {
                            Id = 55,
                            ImagePath = "https://localhost:7119/MakeIcons\\fiat.svg",
                            Name = "Fiat",
                            ProducingCountryId = 7
                        },
                        new
                        {
                            Id = 56,
                            ImagePath = "https://localhost:7119/MakeIcons\\lamborghini.svg",
                            Name = "Lamborghini",
                            ProducingCountryId = 7
                        },
                        new
                        {
                            Id = 57,
                            ImagePath = "https://localhost:7119/MakeIcons\\maserati.svg",
                            Name = "Maserati",
                            ProducingCountryId = 7
                        },
                        new
                        {
                            Id = 58,
                            ImagePath = "https://localhost:7119/MakeIcons\\saab.svg",
                            Name = "Saab",
                            ProducingCountryId = 8
                        },
                        new
                        {
                            Id = 59,
                            ImagePath = "https://localhost:7119/MakeIcons\\volvo.svg",
                            Name = "Volvo",
                            ProducingCountryId = 8
                        },
                        new
                        {
                            Id = 60,
                            ImagePath = "https://localhost:7119/MakeIcons\\aston martin.svg",
                            Name = "Aston Martin",
                            ProducingCountryId = 9
                        },
                        new
                        {
                            Id = 61,
                            ImagePath = "https://localhost:7119/MakeIcons\\bentley.svg",
                            Name = "Bentley",
                            ProducingCountryId = 9
                        },
                        new
                        {
                            Id = 62,
                            ImagePath = "https://localhost:7119/MakeIcons\\land rover.svg",
                            Name = "Land Rover",
                            ProducingCountryId = 9
                        },
                        new
                        {
                            Id = 63,
                            ImagePath = "https://localhost:7119/MakeIcons\\rolls royce.svg",
                            Name = "Rolls Royce",
                            ProducingCountryId = 9
                        },
                        new
                        {
                            Id = 64,
                            ImagePath = "https://localhost:7119/MakeIcons\\mini.svg",
                            Name = "Mini",
                            ProducingCountryId = 9
                        },
                        new
                        {
                            Id = 65,
                            ImagePath = "https://localhost:7119/MakeIcons\\mclaren.svg",
                            Name = "McLaren",
                            ProducingCountryId = 9
                        },
                        new
                        {
                            Id = 66,
                            ImagePath = "https://localhost:7119/MakeIcons\\seat.svg",
                            Name = "Seat",
                            ProducingCountryId = 10
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MakeId = 1,
                            Name = "5 series"
                        },
                        new
                        {
                            Id = 2,
                            MakeId = 2,
                            Name = "4Runner"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.ModelGeneration", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.HasKey("ModelId", "GenerationId");

                    b.HasIndex("GenerationId");

                    b.ToTable("ModelGeneration");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            GenerationId = 1
                        },
                        new
                        {
                            ModelId = 1,
                            GenerationId = 2
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Modification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Modifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelId = 1,
                            Name = "520i AT (150 hp)"
                        },
                        new
                        {
                            Id = 2,
                            ModelId = 1,
                            Name = "520i MT (150 hp)"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.ProducingCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProducingCountries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Німеччина"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Японія"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Франція"
                        },
                        new
                        {
                            Id = 4,
                            Name = "США"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Корея"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Чехія"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Італія"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Швеція"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Англія"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Іспанія"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.TechnicalCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Пошкодження або раніше відремонтовані пошкодження відсутні",
                            Name = "Повністю непошкоджене"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Пошкодження усунуті, не потребує ремонту",
                            Name = "Професійно відремонтовані пошкодження"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Після ДТП, сліди граду, пошкодження кузова, несправність рульового управління, коробки передач, осей і т.д.",
                            Name = "Не відремонтовані пошкодження"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Через ДТП, пожежу, несправності двигуна і т.д.",
                            Name = "Не на ходу / На запчастини"
                        });
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Car", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.BodyType", "BodyType")
                        .WithMany("Cars")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.DriveTrain", "DriveTrain")
                        .WithMany("Cars")
                        .HasForeignKey("DriveTrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.FuelType", "FuelType")
                        .WithMany("Cars")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.GearBoxType", "GearBoxType")
                        .WithMany("Cars")
                        .HasForeignKey("GearBoxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.Generation", "Generation")
                        .WithMany("Cars")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.Modification", "Modification")
                        .WithMany("Cars")
                        .HasForeignKey("ModificationId")
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.TechnicalCondition", "TechnicalCondition")
                        .WithMany("Cars")
                        .HasForeignKey("TechnicalConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId");

                    b.Navigation("BodyType");

                    b.Navigation("DriveTrain");

                    b.Navigation("FuelType");

                    b.Navigation("GearBoxType");

                    b.Navigation("Generation");

                    b.Navigation("Model");

                    b.Navigation("Modification");

                    b.Navigation("TechnicalCondition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Images", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Make", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.ProducingCountry", "ProducingCountry")
                        .WithMany("Makes")
                        .HasForeignKey("ProducingCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProducingCountry");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Model", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.ModelGeneration", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.Generation", "Generation")
                        .WithMany("ModelGenerations")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.Model", "Model")
                        .WithMany("ModelGenerations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Modification", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.Model", "Model")
                        .WithMany("Modifications")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Server.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoMarket.Server.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.BodyType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Car", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.DriveTrain", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.FuelType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.GearBoxType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Generation", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("ModelGenerations");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Make", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Model", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("ModelGenerations");

                    b.Navigation("Modifications");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.Modification", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.ProducingCountry", b =>
                {
                    b.Navigation("Makes");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.TechnicalCondition", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoMarket.Server.Core.Models.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
